---
:concurrency: 5
:url: <%= ENV.fetch("REDIS_HOST", 'redis://localhost:6379')%>
:password: <%= ENV.fetch("REDIS_PASSWORD", 'password')%>
staging:
  :concurrency: 5
:queues:
  - critical
  - default
  - low

production:
  :concurrency: 5