Style/StringLiterals:
  Exclude:
    - db/schema.rb
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - app/admin/*
    - Gemfile
    - db/schema.rb
    - config/deploy.rb
    - spec/**/*
Layout/LineLength:
  Exclude:
    - Gemfile
    - config/deploy.rb
    - config/initializers/devise.rb